Dev
parkbearpark/sophia-cancel-announcement-bot pull request #1
Opened 2020-02-13 03:22 UTC by parkbearpark

コードレビュー

2020-02-14 12:35 UTC, Tsutomu-Ikeda commented on .env.example
> +ACCESS_TOKEN_SECRET=
最後は改行で終わった方が良いよー

2020-02-14 13:19 UTC, Tsutomu-Ikeda requested changes
全体的によく書けてる！

2020-02-14 13:19 UTC, Tsutomu-Ikeda commented on .gitignore
> +__pycache__
ここも同様に改行で終わらせる

2020-02-14 13:19 UTC, Tsutomu-Ikeda commented on dockerfile
> +CMD ["python", "__main__.py"]
改行で終わらせる

2020-02-14 13:19 UTC, Tsutomu-Ikeda commented on setup.cfg
> +    selenium
改行で終わらせる

2020-02-14 13:19 UTC, Tsutomu-Ikeda commented on src/__main__.py
> +    print('start')
```
import logging
```
した後、
```
logging.info('start')
```
の方が良いと思う

2020-02-14 13:19 UTC, Tsutomu-Ikeda commented on dockerfile
> +CMD ["python", "__main__.py"]
後、Dockerfileって通常のファイル名だと先頭大文字では…？

2020-02-14 13:19 UTC, Tsutomu-Ikeda commented on test/conftest.py
> +sys.path.append(os.path.join(os.path.dirname(__file__), '../src'))
これくらいならまだos.pathでも良いけど、これ以上複雑になる場合はpathlibを使い、ちゃんと変数を作った方が見やすい。
```
from pathlib import Path

src_path_abs = (Path(__file__) / '../src').resolve()
sys.path.append(str(src_path_abs))
```

2020-02-14 13:19 UTC, Tsutomu-Ikeda commented on src/twitter.py
> +            print(request.text)
ここ謎

2020-02-14 13:19 UTC, Tsutomu-Ikeda commented on src/__main__.py
> +    print('finish')
```
import logging

logging.info(pprint.pformat(tweet_list))
logging.info('finish')
```
とすると良いと思う。

2020-02-14 13:19 UTC, Tsutomu-Ikeda commented on src/__main__.py
> +            ret_str = re.sub('　', ' ', ret_str)
正規表現を使うなら、
```
result = re.sub('[\u3000  　]', ' ', _str)
```
で良いのでは

2020-02-14 13:19 UTC, Tsutomu-Ikeda commented on src/__main__.py
> +            fetch_text_data(lower_xpath_base + 'tr[5]/td[2]')
```
course_info = {
  'course_affiliation': fetch_text_data(upper_xpath_base + 'tr[1]/td')
  'course_name': fetch_text_data(upper_xpath_base + 'tr[2]/td[1]')
  ...
}
```
とした方が見やすいと思う

2020-02-14 13:19 UTC, Tsutomu-Ikeda commented on src/__main__.py
> +        time.sleep(3)  # HACK: これ書かんと動かないことがあるけど他に方法ないんか
https://qiita.com/uguisuheiankyo/items/cec03891a86dfda12c9a

implicitly_wait 使うと行けるかも

2020-02-17 13:51 UTC, parkbearpark commented on dockerfile
> +CMD ["python", "__main__.py"]
本当ですねなぜか小文字でも動いてたけど、、、

2020-02-17 14:06 UTC, parkbearpark commented on src/twitter.py
> +            print(request.text)
書いた覚えのないものが入ってて草
本当に謎だ、、、

2020-02-17 14:27 UTC, parkbearpark commented on src/__main__.py
> +        time.sleep(3)  # HACK: これ書かんと動かないことがあるけど他に方法ないんか
implicitly_wait ってドライバに対して最大の待ち時間を一律で設定するからこの場合だとすでに15sで設定してるのが動かないんですよね、、、

2020-03-09 17:31 UTC, merged